name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux-x86_64
          - os: ubuntu-22.04-arm
            target: linux-aarch64
          - os: macos-15-intel
            target: macos-x86_64
          - os: macos-15
            target: macos-aarch64
          - os: windows-2022
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: cargo test
